import type { Metadata } from "next";
import "./globals.css";
import ReactLenis from "lenis/react";
import { languages } from "../i18n/settings";
import { dir } from "i18next";

export async function generateStaticParams() {
  return languages.map((lang) => ({ lang }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={lang} dir={dir(lang)}>
      <ReactLenis root>
        <body>{children}</body>
      </ReactLenis>
    </html>
  );
}
